### ISSUE TITLE
Trezor is locked.

### ISSUE THREAD

**Issue by qustavo** [nunchuk-io/libnunchuk#1]
I'm running nunchuck 0.9.3 on linux and I'm getting this message when trying to refresh devices:
> Could not open client or get fingerprint information: Trezor is locked. Unlock by using 'promptpin' and then

Any hint?

**Comment by hugohn** [comment]
Hi @gchaincl , are you using Trezor One or Trezor T? And is it PIN-enabled?

**Comment by qustavo** [comment]
It's a Trezor One, pin enabled

**Comment by hugohn** [comment]
@gchaincl Unfortunately currently we only support the Trezor One in no-PIN mode (as the Trezor One can't use its own display for PIN input). We might add this to Nunchuk in the near future.

(FWIW, Trezor T is more secure than Trezor One for this reason. Entering PIN directly on the Trezor is safer than entering PIN on a host device.)

**Comment by qustavo** [comment]
Ok, thanks!
