### ISSUE TITLE
Multi device wallet does not sync signitures

### ISSUE THREAD

**Issue by Alex71btc** [nunchuk-io/libnunchuk#14]
https://github.com/nunchuk-io/nunchuk-desktop/issues/19#issue-1324823629

**Comment by Alex71btc** [comment]
Hey, did you have any findings why signitures with airgapped keys don't sync in messenger?
I found out, that messenger only sees the signed transaction from the key on local machine that i signed on in desktop app after restarting Nunchuk.Then it shows within messenger the PSBT as signed with one key(the local Key), it also does not send the message "<Username> has signed the transaction with key<fingerprint>" it usually sends when using a software wallet for collab signing.
Software Keys update in messenger and signing works, where airgapped keys seem not to be recognized by messenger.

**Comment by Alex71btc** [comment]
Then maybe also this info helps: when i sign the transaction with Seedsinger on one device by scanning the PSBT with both signers for 2of... wallet, i can not broadcast from within messenger, instead i get this error message:
![Signer](https://user-images.githubusercontent.com/105175715/183300248-ff97a7e3-dc1a-47f6-8916-2bf3492a6ab9.jpg)
But then i can broadcast it from with the wallet interface:
![broadcast](https://user-images.githubusercontent.com/105175715/183300286-bb48868f-9b9a-42ce-bd42-fc97e997e6ed.jpg)

**Comment by hugohn** [comment]
Hey @Funman2 we are still checking this issue internally. Thanks for the additional info! Will keep you posted.

**Comment by hugohn** [comment]
@Funman2 we’ve identified the root cause and will be making a fix soon. It is an issue specific to airgapped signing.

**Comment by Alex71btc** [comment]
Great News! Looking forward.

**Comment by Alex71btc** [comment]
Hey, any news on the fix for airgapped signing?

**Comment by hugohn** [comment]
Yup! Releases coming this week.

**Comment by Alex71btc** [comment]
Awesome!



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Hugo ***@***.***>
Datum: 25.09.22 11:03 (GMT+01:00)
An: nunchuk-io/libnunchuk ***@***.***>
Cc: Funman2 ***@***.***>, Mention ***@***.***>
Betreff: Re: [nunchuk-io/libnunchuk] Multi device wallet does not sync signitures (Issue #14)


Yup! Releases coming this week.

**Comment by hugohn** [comment]
@Funman2 Fyi, the mobile apps with the fix are out. Desktop will follow shortly.

https://twitter.com/nunchuk_io/status/1574977342698496000

**Comment by Alex71btc** [comment]
Great! Will check it out asap.

**Comment by Alex71btc** [comment]
Congratulations Nunchuk! I got little time today to do first tests with desktop and mobile app for collab signing with airgapped key (seedsigner), so far it worked flawless! Awesome job you did here, that´s now a very sophisticated wallet to use for secure multisig.
(At first i had some problems with the desktop app, because it did not take over my data from the previous nunchuk version and i could not log in, also guest account was kind of missing, but then I erased out all old data from the nunchuk folder and could log in to my account with no problems. Also when I start the messenger with the desktop app first, then mobile,setting up the collab wallet, I get no problems with encryption at all as well and signing really works like a charm now. 
Tomorrow i will test more and explore guest mode again.)
 I am very exited for all the great options in collab multisig now! This wallet is the future. Thx for all your great contributions to the bitcoin space!

**Comment by Alex71btc** [comment]
Hey, I did a lot of testing recently together with tongvanlinh on nunchuk desktop in 2of3 multisig setup together with mobile app(android) .
With the current versions signatures of airgapped keys (seedsigner) sync well from mobile into desktop version( windows) but signatures signed within desktop app don't sync with the android app via messenger still. 
Otherwise it's working  really great now with database encryption and most other features. 
Really thanks for designing such a cool wallet for collab multisig in bitcoin.

**Comment by Alex71btc** [comment]
Works now!
