### ISSUE TITLE
BC-UR export via QR unnecessarily inefficient

### ISSUE THREAD

**Issue by JamieDriver** [nunchuk-io/libnunchuk#18]
Hi,
We've been looking to work with your desktop app via UR/QR messages with Blockstream Jade, and while it's working well, I have a couple of minor suggestions that may make life better for all 'scanning' devices.
Feel free to ignore me ofc - this is just stuff I noticed while developing our side to integrate with QR-friendly apps, particularly areas where I noticed we were having a less pleasant experience with Nunchuk than with some other wallet apps.

a. The UR text appears to be in lower case!  This is bad for QR encoding, as it has to use its most space-inefficient mode (Binary).  UR output (when in uppercase) only uses characters in the QR 'Alphanumeric' encoding mode, so this can be packed into fewer (or lower-res) QRs.  If you turn the entire payload string to uppercase, you'll be able to increase the 'MAX_FRAGMENT_SIZE' and still be using the same size/version QR codes - just far fewer of them!
```
ur:bytes/1-6/lpadamcfaobncydnlkvtlnhdhdhkaoascncxfeksjojljpjyihiecxiyjpjljncxglkpjtiaiskpjebkglhsjnihftcxgehsieihcxgtkpjzjyinbkgdjljziniakkftcxeycxjliycxeobkfgjljpjnhsjyftcxgdeyhggufdbkbkfyihjpinkohsjyinjljtftcxjndlahdipysp
```
^ This particular multisig wallet output takes 6 QR codes in Nunchuk - 2 in many other wallets, and one case just one!  (All other wallets I tested with are using uppercase payloads and 'Alphanumeric' QR mode - resulting in far fewer fragments/QR codes).

b. I notice that the UR fragment creation stops when `encoder.is_complete()`.  ie. you produce the minimum number of fragments to convey the data payload, and no more - you don't produce any fountain-code fragments whatsoever.
This is bad for scanning devices as it leads to the 'coupon collectors problem' (where we have to play through the animation of N frames when we only need one particular frame/fragment).
The addition of fountain code fragments (as intended by BC/UR) addresses this issue, as reading a fountain-code fragment allows the scanner to reconstitute virtually *any* missing frame.
eg. as it stands, if a psbt needs say 10 fragments, but I miss one or two fragments, I have to watch the entire cycle again hoping to catch those fragments next time around.  If not, we have to play the sequence again ...
With fountain-code frames, you may produce say 20 fragments (10 'pure data' [as currently], and 10 'fountain codes'), and again I miss one or two frames ... so long as I successfully scan (pretty much) *any* one or two of the following fountain-code fragments I will be able to reconstitute the missing fragment(s) and complete.  ie. you produce 20 frames but the scanner only needs to pick up *any 10* of them.
This is all handled by the BC-UR lib and needs no additional code in-app, other than deciding how many fountain-code frames to append.

^ The combination of these factors is a bit of a worse-case scenario - a) means we need to scan an unnecessarily large number of QR codes, and b) means we have to collect every single one of them (rather than say, any 60% of them). 

I'd be interested to hear your thoughts.
Cheers.

**Comment by hugohn** [comment]
Thanks @JamieDriver for the suggestions / feedback! We'll take a look and get back shortly.

**Comment by hugohn** [comment]
Resolved.
