### ISSUE TITLE
Can't add BitBox02

### ISSUE THREAD

**Issue by bogorad** [nunchuk-io/libnunchuk#19]
Latest versions of the BitBox app (4.35.1) and the BitBoxBridge app (1.5.0). Nunchuck finds the key, requests I sign a message, then receives the signature, then fails:

![Screenshot 2022-12-06 181710](https://user-images.githubusercontent.com/2777398/205979429-2a20baac-d78c-4944-b701-bf6d1d5baceb.png)

The message appears only for a second, I had to screenshot it quickly (succeeded only on the third try).

**Comment by cdmoss** [comment]
I'm getting this too
