### ISSUE TITLE
Ledger Nano S not detected

### ISSUE THREAD

**Issue by starsoccer** [nunchuk-io/libnunchuk#2]
When trying to add new signers my ledger nano S is not detected, I unlocked the device and selected the bitcoin app. Other HW wallets seem to be detected fine such as trezor.

**Comment by bakaoh** [comment]
hi @starsoccer , what nunchuk app version are you using? and what OS?

It seems related to this issue https://github.com/bitcoin-core/HWI/issues/402 
we gonna update HWI to latest version (1.2.1) in next release, it should fix the problem

**Comment by starsoccer** [comment]
0.9.3 and Windows 10

It looks like there is a new version out already, I can try that, it would be useful if you had a release notes somewhere on the site.

**Comment by starsoccer** [comment]
Tested the new build and it seems to work now so closing this

**Comment by LostEden2022** [comment]
Having the same problem, but this time with the current version.
