### ISSUE TITLE
Not showing transactions and balance for a wallet when lots of wallets are added.

### ISSUE THREAD

**Issue by endakh** [nunchuk-io/libnunchuk#30]
My Nunchuk (iOS, iPhone 15, latest version) shows zero balance and no transactions for a wallet that actually has a transaction (quite old and confirmed) and a positive balance.

Seems like it started to occur when I added more than ~70 wallets. When I add the same wallet on another device, it shows the balance and the transactions.

**Comment by Stopstilhen** [comment]
Hello @endakh 
You’re facing possibly version error 
A complaint has be lodged and ticket has been created for you (Ticket number #Nc62892)
Visit the official website to initiate a chat with the support team via [Nunchuk Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generate for you to properly rectify your problem.

**Comment by hugohn** [comment]
If you have more than 70 wallets, the app will need to rotate through all of them to sync with the blockchain and therefore will take a long time to sync.

**Comment by Hushg2** [comment]
Hello @endakh  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
